# Generated by Django 6.1.1 on 2026-09-17 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='logisticsubtask',
            options={'ordering': ['scheduled_date'], 'verbose_name': 'Subtarea logística', 'verbose_name_plural': 'Subtareas logísticas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(help_text='Fecha en la que ocurre el evento (distinta de las fechas de sus subtareas).'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Nombre del evento.', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planning', 'Planeando'), ('in_progress', 'En curso'), ('finished', 'Finalizado')], default='planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(help_text='Usuario dueño del evento. Al eliminar el usuario, se eliminan sus eventos.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logisticsubtask',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=1, help_text='Horas estimadas para completar la gestión. Se usa en el cálculo de conflicto (T3).'),
        ),
        migrations.AlterField(
            model_name='logisticsubtask',
            name='event',
            field=models.ForeignKey(help_text='Evento al que pertenece esta gestión logística.', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='eventos.event'),
        ),
        migrations.AlterField(
            model_name='logisticsubtask',
            name='note',
            field=models.TextField(blank=True, help_text='Comentario opcional sobre el avance (ej. por qué se pospuso).', null=True),
        ),
        migrations.AlterField(
            model_name='logisticsubtask',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='logisticsubtask',
            name='scheduled_date',
            field=models.DateField(help_text="Fecha programada para ejecutar la gestión; funciona como el 'plazo' de T1 y es el campo que se actualiza al reprogramar (T3)."),
        ),
        migrations.AlterField(
            model_name='logisticsubtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('done', 'Hecho'), ('postponed', 'Pospuesto')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='logisticsubtask',
            name='type',
            field=models.CharField(choices=[('book_venue', 'Reservar salón'), ('send_invitations', 'Enviar invitaciones'), ('confirm_catering', 'Confirmar catering'), ('coordinate_vendors', 'Coordinar proveedores'), ('other', 'Otro')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='logisticsubtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada cambio; sirve como rastro básico de auditoría.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_hours_limit',
            field=models.PositiveIntegerField(default=6, help_text='Límite de horas diarias que el usuario puede dedicar a gestiones logísticas. Se usa para detectar el conflicto de sobrecarga al reprogramar subtareas (T3).'),
        ),
    ]
