# Generated by Django 6.1.1 on 2026-09-22 17:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_alter_event_options_alter_logisticsubtask_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="contact",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre o datos de contacto del cliente.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("wedding", "Boda"),
                    ("social", "Social"),
                    ("corporate", "Corporativo"),
                    ("birthday", "Cumpleaños"),
                    ("other", "Otro"),
                ],
                default="other",
                help_text="Tipo o categoría del evento.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Lugar físico o plazo límite general del evento.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True, help_text="Descripción o notas del evento.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(
                help_text="Fecha en la que se llevará a cabo el evento."
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planeando"),
                    ("in_progress", "En curso"),
                    ("finished", "Finalizado"),
                ],
                default="planning",
                help_text="Estado actual del evento.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                help_text="Usuario propietario del evento.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="logisticsubtask",
            name="estimated_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("1.0"),
                help_text="Horas estimadas de trabajo (mayor a 0, entero o decimal simple).",
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
            ),
        ),
        migrations.AlterField(
            model_name="logisticsubtask",
            name="event",
            field=models.ForeignKey(
                help_text="Evento al que pertenece esta gestión.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="eventos.event",
            ),
        ),
        migrations.AlterField(
            model_name="logisticsubtask",
            name="name",
            field=models.CharField(
                help_text="Nombre de la gestión logística.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="logisticsubtask",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Nota de avance o motivo de postergación.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="logisticsubtask",
            name="priority",
            field=models.CharField(
                choices=[("low", "Baja"), ("medium", "Media"), ("high", "Alta")],
                default="medium",
                help_text="Nivel de prioridad de la gestión.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="logisticsubtask",
            name="scheduled_date",
            field=models.DateField(
                help_text="Fecha objetivo o plazo planificado para ejecutar la gestión."
            ),
        ),
        migrations.AlterField(
            model_name="logisticsubtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("in_progress", "En progreso"),
                    ("done", "Hecho"),
                    ("postponed", "Pospuesto"),
                ],
                default="pending",
                help_text="Estado de ejecución de la gestión.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="logisticsubtask",
            name="type",
            field=models.CharField(
                choices=[
                    ("book_venue", "Reservar salón"),
                    ("send_invitations", "Enviar invitaciones"),
                    ("confirm_catering", "Confirmar catering"),
                    ("coordinate_vendors", "Coordinar proveedores"),
                    ("other", "Otro"),
                ],
                default="other",
                help_text="Tipo de gestión logística.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="logisticsubtask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="daily_hours_limit",
            field=models.PositiveIntegerField(
                default=6,
                help_text="Límite de horas diarias que el usuario puede dedicar a gestiones logísticas.",
            ),
        ),
    ]
