# Generated by Django 6.1.1 on 2026-10-06 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_event_contact_event_event_type_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_hours_limit',
            field=models.PositiveIntegerField(default=6, help_text='Límite de horas diarias que el usuario puede dedicar a gestiones logísticas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
    ]
